checkpoint_1: testing_protocols
IgorZhiltsoff/TPy_project pull request #1
Opened 2022-03-20 17:01 UTC by IgorZhiltsoff

Implemented 4/4 testing protocols + 2 tests for each
Displayed a UML diagram with testing protocols hierarchy

2022-03-25 06:14 UTC, IgorZhiltsoff commented
TP: Last commit before 1st CHECKPOINT DEADLINE: [da81285](https://github.com/IgorZhiltsoff/TPy_project/pull/1/commits/da8128571f9948b1ffb3decb7c27add7362b5f74)

2022-03-27 19:59 UTC, IgorZhiltsoff commented
PYTHON: Last commit before 1st REVIEW DEADLINE: [97e20c4](https://github.com/IgorZhiltsoff/TPy_project/pull/1/commits/97e20c49be73b8d33df1efd96881f2fa6ac79e24)
PYTHON: Next commit after DEADLINE with normal README.md: [230c3a2](https://github.com/IgorZhiltsoff/TPy_project/pull/1/commits/230c3a2104fcb3f4334865d50d2eba93de576913)

2022-03-29 00:45 UTC, VTroyanGolovyan approved these changes
Я не нашел где у тебя защита реализована.

нужно убрать мусор, и посмотреть внимательно на копипасту одинаковых кусков кода

пока ставлю 9

2022-03-29 00:45 UTC, VTroyanGolovyan commented on TestingSystem/TestingProtocols/.idea/TestingProtocols.iml
> +    </content>
мусор

2022-03-29 00:45 UTC, VTroyanGolovyan commented on TestingSystem/TestingProtocols/.idea/inspectionProfiles/profiles_settings.xml
> +    <option name="USE_PROJECT_PROFILE" value="false" />
мусор

2022-03-29 00:45 UTC, VTroyanGolovyan commented on TestingSystem/TestingProtocols/.idea/misc.xml
> +  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3.10 (classes)" project-jdk-type="Python SDK" />
мусор

2022-03-29 00:45 UTC, VTroyanGolovyan commented on TestingSystem/TestingProtocols/sample_tests/test_python3.py
> +        self.assertEqual('AC', inout.check(user_submitted_data=correct).msg)
у тебя эта штука копипастой по всему проекту, подумай как от этого отойти

2022-04-04 10:13 UTC, SokG2000 requested changes
Напиши простую программу, использующую эту библиотеку.

2022-04-04 10:13 UTC, SokG2000 commented on TestingSystem/TestingProtocols/sample_tests/test_python3.py
> +from testing_protocols import InputOutput, InputCustomChecker, RandomInputCustomChecker, LimitedWorkSpace, \
Добейся того чтобы import работал при запуске файла с тестами интерпретатором питона или сделай инструкцию по запуску тестов. Разумеется при этом не надо ломать структуру проекта (например, перекладывать все файлы в одну папку). Наверное, самый правильный вариант - разобраться как работает import в python и как импортировать файлы из другой папки.

2022-04-04 10:13 UTC, SokG2000 commented on TestingSystem/TestingProtocols/testing_protocols.py
> +        test = 0
Лучше for tests, path_to_input_file in enumerate(self.input_output_paths_dict)

2022-04-05 20:19 UTC, IgorZhiltsoff commented on TestingSystem/TestingProtocols/sample_tests/test_python3.py
> +from testing_protocols import InputOutput, InputCustomChecker, RandomInputCustomChecker, LimitedWorkSpace, \
Добавил bash-скрипты, запускающие тесты (TestingSystem/TestingProtocols/run_*_tests.py)
(Команда PYTHONPATH=<src> python3 script.py запускает скрипт с кастомным путем для поиска файлов)

2023-05-25 22:21 UTC, merged